[package]
name = "websocket_echoer"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.*"
fastwebsockets = { version = "0.8.*", features = ["upgrade", "with_axum"] }
tokio = { version = "1.*", features = ["macros", "rt-multi-thread"] }


